##############################################################################################################
# Common project docker build options.
# This builds the docker images which may be used locally within the swarm or in the AWS container service
##############################################################################################################
services:
  ##############################################################################################################
  # Wildlife licencing API service
  # The development version of the service runs the webpack post-process to install the
  # Open API browser
  ##############################################################################################################
  api:
    image: wildlife-licencing/api:${TAG:-latest}
    build:
      context: ../packages/api
      dockerfile: ${PROJECT_DOCKERFILE:-Dockerfile.dev}

  ##############################################################################################################
  # Wildlife licencing API service; application queue processor
  ##############################################################################################################
  aqp:
    image: wildlife-licencing/aqp:${TAG:-latest}
    build:
      context: ../packages/application-queue-processor
      dockerfile: ${PROJECT_DOCKERFILE:-Dockerfile.dev}

  ##############################################################################################################
  # Wildlife licencing API service; application extract processor
  ##############################################################################################################
  aep:
    image: wildlife-licencing/aep:${TAG:-latest}
    build:
      context: ../packages/application-extract-processor
      dockerfile: ${PROJECT_DOCKERFILE:-Dockerfile.dev}

  ##############################################################################################################
  # Wildlife licencing API service; reference data extract processor
  ##############################################################################################################
  rep:
    image: wildlife-licencing/rep:${TAG:-latest}
    build:
      context: ../packages/refdata-extract-processor
      dockerfile: ${PROJECT_DOCKERFILE:-Dockerfile.dev}

  ##############################################################################################################
  # Wildlife licencing Web service
  ##############################################################################################################
  web:
    image: wildlife-licencing/web:${TAG:-latest}
    build:
      context: ../packages/web-service
      dockerfile: ${PROJECT_DOCKERFILE:-Dockerfile.dev}